// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public int? ZipCode { get; set; }

    public string City { get; set; }

    public string Address1 { get; set; }

    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    public virtual ICollection<Work> Work { get; set; } = new List<Work>();
}