// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class AppUser
{
    public int AppUserId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Profession { get; set; }

    public bool IsAdmin { get; set; }

    public string AspNetUserId { get; set; }

    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    public virtual ICollection<Work> Work { get; set; } = new List<Work>();
}