// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class Cim
{
    public int CimId { get; set; }

    public int? Iranyitoszam { get; set; }

    public string Telepules { get; set; }

    public string UtcaHazszam { get; set; }

    public virtual ICollection<Munka> Munka { get; set; } = new List<Munka>();

    public virtual ICollection<Ugyfel> Ugyfel { get; set; } = new List<Ugyfel>();
}