// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;

using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class Felhasznalo : IdentityUser
{
    public string Nev { get; set; }

    public string Tevekenyseg { get; set; }

    public bool IsAdmin { get; set; }
}