// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class Felhasznalo
{
    public int FelhasznaloId { get; set; }

    public string Jelszo { get; set; }

    public string Nev { get; set; }

    public string Email { get; set; }

    public string Tevekenyseg { get; set; }

    public bool IsAdmin { get; set; }

    public virtual ICollection<Munka> Munka { get; set; } = new List<Munka>();

    public virtual ICollection<Ugyfel> Ugyfel { get; set; } = new List<Ugyfel>();
}