// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class Munka
{
    public int MunkaId { get; set; }

    public string MunkaMegnevezes { get; set; }

    public int? UgyfelId { get; set; }

    public DateTime? Idopont { get; set; }

    public string Leiras { get; set; }

    public int? CimId { get; set; }

    public int? StatuszId { get; set; }

    public string FelhasznaloId { get; set; }

    public int? Ar { get; set; }

    public virtual Cim Cim { get; set; }

    public virtual MunkaStatusz Statusz { get; set; }

    public virtual Ugyfel Ugyfel { get; set; }

    public virtual Felhasznalo Felhasznalo { get; set; }
}