// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class MunkaStatusz
{
    public int MunkaStatuszId { get; set; }

    public string StatuszMegnevezes { get; set; }

    public virtual ICollection<Munka> Munka { get; set; } = new List<Munka>();
}