// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class Ugyfel
{
    public int UgyfelId { get; set; }

    public string Nev { get; set; }

    public string Email { get; set; }

    public int? CimId { get; set; }

    public int FelhasznaloId { get; set; }

    public virtual Cim Cim { get; set; }

    public virtual Felhasznalo Felhasznalo { get; set; }

    public virtual ICollection<Munka> Munka { get; set; } = new List<Munka>();
}