// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Epic.CRM.DataDomain.Models;

public partial class WorkStatus
{
    public int WorkStatusId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Work> Work { get; set; } = new List<Work>();
}